chore: dependency updates and fixes (#110)
* docs: format and extend `README.md`

adds info about generating `./js/src/constraints.ts`

* chore: ignore python `venv`

* chore: update root dependencies

* chore: update `js` dependencies and fix errors

* fix: word-splitting in `concat_lp.sh`

* chore: pin `pyyaml` to version `5.4.1`

getting `TypeError: load() missing 1 required positional argument: 'Loader'` otherwise

* fix: `tests/test_run.py`

* style: format code

* ci: use `node` 16